# docker compose spec
# https://github.com/compose-spec/compose-spec/blob/master/spec.md
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#extension
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#fragments

# airflow configs
# https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#webserver

# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
---
version: '3.7'
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.3.3-python3.9}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 10
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/data
    - ./mlflow:/mlflow
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    
  airflow-init:
    <<: *airflow-common
    build:
      context: ./docker/airflow-base
    image: instork/airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins /sources/data /sources/mlflow
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins,data,mlflow}
        exec /entrypoint airflow version
    env_file:
      - airflow.env
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      # set below on airflow.env
      # _AIRFLOW_WWW_USER_USERNAME: your_username
      # _AIRFLOW_WWW_USER_PASSWORD: your_pwd
    user: "0:0"
    volumes:
      - .:/sources
      
  airflow-webserver:
    <<: *airflow-common
    build:
      context: ./docker/airflow-base
    image: instork/airflow-webserver
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8085/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    build:
      context: ./docker/airflow-scheduler
    image: instork/airflow-scheduler
    command: scheduler
    restart: always

  mongodb:
    hostname: mongoservice
    container_name: mongodb
    image: mongo:4.4.15
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=airflow
      - MONGO_INITDB_ROOT_PASSWORD=airflow
      - MONGO_INITDB_DATABASE=mydb
    
volumes:
  postgres-db-volume: